### ISSUE TITLE
[Request] Change the width and height steps to 128

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [kijai/ComfyUI-DiffusersStableCascade#5]
Because of the way sizes are used in Cascade, there is an error thrown if you don't get it correct. If you change the multiple of the width and height to step in units of 128, instead of 8, then this bypasses the errors.

Example error:
`RuntimeError: pixel_unshuffle expects height to be divisible by downscale_factor, but input.size(-2)=277 is not divisible by 2`

**Comment by kijai** [comment]
I was wondering what it should be, thanks, done!

**Comment by GalaxyTimeMachine** [comment]
The update may have broken it...

```
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\nodes.py", line 13
    <<<<<<< Updated upstream
IndentationError: expected an indented block after function definition on line 12
```

**Comment by GalaxyTimeMachine** [comment]
Thanks! :)
